services:
  fiboaitech-app:
    image: fiboaitech-app:${IMAGE_TAG:-local}
    build:
      target: develop
    volumes:
      - ./:/app

  fiboaitech-app-test:
    image: fiboaitech-app:${IMAGE_TAG:-local}
    build:
      target: develop
    entrypoint: ["make", "test"]
    env_file:
      - .env
    volumes:
      - ./:/app

  fiboaitech-app-test-cov:
    image: fiboaitech-app:${IMAGE_TAG:-local}
    build:
      target: develop
    entrypoint: ["make", "test-cov"]
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./reports:/app/reports:wr
