name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file on push or internal PR
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          envkey_UNSTRUCTURED_API_KEY: ${{ secrets.UNSTRUCTURED_API_KEY }}
          envkey_PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          envkey_PINECONE_CLOUD: ${{ secrets.PINECONE_CLOUD }}
          envkey_PINECONE_REGION: ${{ secrets.PINECONE_REGION }}

      - name: Create .env file on fork PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: SpicyPizza/create-envfile@v2.0

      - name: Build
        uses: docker/bake-action@v5
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          targets: fiboaitech-app
